### PR TITLE
IAM roles for swarm master and swarm slaves

### PR DESCRIPTION
**Pull request by itamararjuan**
This PR allows the swarm master slaves the following permissions within an aws role:

- Pull Docker images from within all available ECRs in the AWS account
- Read secrets from the secrets manager

In addition, the swarm managers/masters have the following permissions also defined within a separate manager role:
- Pull Docker images from within all available ECRs in the AWS account
- Read and Write secrets from the Secrets Manager

-- Itamar

### CODE REVIEW

**Comment by netoneko** [comment]
Why commit `get-pip.py`?

**Comment by netoneko** [comment]
`shortenedContext` is very problematic because it's not unique which prevents us from running in the regions that end by the same 6 letters.

**Comment by itamararjuan** [comment]
The `shortenedContext` is supposed to make sense the federation members who will be using these tools. Bare in mind companies who have existing infrastructure running and want to make sure they are looking at the correct resources that nebula just provisioned for them. But none-the-less I understand your situation. I will see what I can do to make sure your approach of using a mutable directory that exists before running nebula is unhurt. Please remember this approach only applies within Orbs and not on the outside.

**Comment by itamararjuan** [comment]
`get-pip.py` was commited by mistake. I will delete that. good catch!

**Pull request merged**
